version: '3.7'
services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
    volumes:
      - ../Data/config:/config
      - ../Data/movies:/data/movies
      - ../Data/tv:/data/tv
      - ../Data/music:/data/music
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    labels:
      # Traefik Labels
      - "traefik.enable=true"
      # HTTPS Labels
      - "traefik.http.routers.jellyfin.rule=Host(`localhost`)" # Domain Name
      - "traefik.http.routers.jellyfin.entrypoints=web-secure"
      - "traefik.http.routers.jellyfin.middlewares=default-headers@file"
      - "traefik.http.routers.jellyfin.service=jellyfin"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096" # Proxied Port
